const USER_LIST_LOADING = "USER_LIST_LOADING";
const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
const USER_LIST_ERRORED = "USER_LIST_ERRORED";
const USER_LIST_LOGOUT = "USER_LIST_LOGOUT";
const USER_LIST_ADD = "USER_LIST_ADD";
const USER_LIST_DELETE = "USER_LIST_DELETE";

const LOGIN_PROCESSING = "LOGIN_PROCESSING";
const LOGIN_SUCCEED = "LOGIN_SUCCEED";
const LOGIN_FAILED = "LOGIN_FAILED";

export {
  USER_LIST_ERRORED,
  USER_LIST_SUCCESS,
  USER_LIST_LOADING,
  USER_LIST_LOGOUT,
  USER_LIST_ADD,
  USER_LIST_DELETE,
  LOGIN_PROCESSING,
  LOGIN_SUCCEED,
  LOGIN_FAILED
};
